kafka:
  bootstrap-servers: xits-ipmd02.med.cornell.edu:29092
  consumer:
    auto-offset-reset: earliest
    group-id: kafka-dispatcher-manuele
    enable-auto-commit: true
    topics: oncorseq_sequencing_pipeline_initialized,oncorseq_sequencing_in_progress,oncorseq_sequencing_analysis_started

server:
  port: 8443
  ssl:
    key-store: /keystore.p12
    key-store-password: abcdef12
    keyStoreType: PKCS12
    keyAlias: tomcat
  servlet:
    context-path: /dispatcher

dispatcher:
  mode: NON_BLOCKING
  topics:
    - name: oncorseq_sequencing_in_progress
      actions:
        - trigger: nextflow main.nf --sampleID ${sampleID} --run ${runID} --sayHello ${sayHello}
          workingDir: /Users/mas2182/
          reply:
            topic:  oncorseq_sequencing_pipeline_initialized
            payload: sampleID=${sampleID}
    - name: oncorseq_sequencing_pipeline_initialized
      actions:
        - trigger: https://dzone.com/articles/kafka-cluster-1?q=${query}
          reply:
            topic: annotation_started
            payload: search started with ${query}
    - name: oncorseq_sequencing_analysis_started
      actions:
        - trigger: command/URL for analysis_started
          reply:
            topic: analysis_in_progress
            payload: ${sampleID}