---
actions:
- topic: seq_done
  messages:
    - message: sample_ready
      trigger: nextflow main.nf --sampleID=${payload}
    - message: sample_failed
      trigger: https://mymicroservice/name/api?param=value&sampleID=${payload}
    - message: sample_processed
      trigger: whatever you want with ${payload}
- topic: topicB
  messages:
    - message: messageB.1
      trigger: command/URL for B.1
    - message: messageB.2
      trigger: command/URL for B.2
    - message: messageB.3
      trigger: command/URL for B.3

- topic: topicC
  messages:
    - message: messageC.1
      trigger: command/ URL for C.1
    - message: messageC.2
      trigger: command/URL for C.2
    - message: messageC.3
      trigger: command/URL for C.3

kafka:
  broker: kafka.med.cornell.edu:9092
  groupId: consumerGroup1
