event-hubs-connection-string: "Endpoint=sb://XXX.servicebus.windows.net/;SharedAccessKeyName=XXX;SharedAccessKey=XXX"
event-hubs-fqdn: "XXX.servicebus.windows.net"


kafka:
  bootstrap-servers: ${event-hubs-fqdn}:9093
  properties:
    sasl.mechanism: PLAIN
    sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${event-hubs-connection-string}";'
    security.protocol: SASL_SSL
  consumer:
    auto-offset-reset: earliest
    enable-auto-commit: true
    max-records: 10
    group-id: kafka-dispatcher
    missing-topics-fatal: false
    topics: lims-messages2

server:
  port: 8443
  servlet:
    context-path: /dispatcher
  ssl:
    key-store: /config/kd-keystore.jks
    key-store-password: <my password>
    keyStoreType: PKCS12
    keyAlias: kafka-dispatcher-certificate

dispatcher:
  mode: NON_BLOCKING
  service:
    topics:
      - name: lims-messages2
        actions:
          - trigger: https://dzone.com/articles/kafka-cluster-1?user=${user}&password=${password}

  schedulers:
    enable: true
    cron:
      job1:
        active: true
        when: '*/10 * * * * ?'
        actions:
          - trigger: echo "cron job1 started at $(date)" >> /Users/manuelesimi/EIPM/DispatcherSuite/kafka-service/jobs.txt
      job2:
        active: true
        when: '*/20 * * * * ?'
        actions:
          - trigger: echo "cron job2 started at $(date)" >> /Users/manuelesimi/EIPM/DispatcherSuite/kafka-service/jobs.txt
    fixed:
      job1:
        active: true
        when: '10000'
        actions:
          - trigger: now=`date` && echo "fixed job1 started at ${now}" >> /Users/manuelesimi/EIPM/DispatcherSuite/kafka-service/jobs.txt
      job2:
        active: true
        when: '12000'
        actions:
          - trigger: now=`date` && echo "fixed job2 started at ${now}" >> /Users/manuelesimi/EIPM/DispatcherSuite/kafka-service/jobs.txt
    delay:
      job1:
        active: true
        when: '15000'
        actions:
          - trigger: now=`date` && echo "delay job1 started at ${now}" >> /Users/manuelesimi/EIPM/DispatcherSuite/kafka-service/jobs.txt
      job2:
        active: true
        when: '30000'
        actions:
          - trigger: now=`date` && echo "delay job2 started at ${now}" >> /Users/manuelesimi/EIPM/DispatcherSuite/kafka-service/jobs.txt

logging:
  level:
    org.apache.kafka: INFO
    edu.cornell.eipm.messaging.microservices: TRACE
