event-hubs-connection-string: "Endpoint=sb://XXX.servicebus.windows.net/;SharedAccessKeyName=XXX;SharedAccessKey=XXX"
event-hubs-fqdn: "XXX.servicebus.windows.net"


kafka:
  bootstrap-servers: ${event-hubs-fqdn}:9093
  properties:
    sasl.mechanism: PLAIN
    sasl.jaas.config: 'org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="${event-hubs-connection-string}";'
    security.protocol: SASL_SSL
  consumer:
    auto-offset-reset: earliest
    enable-auto-commit: true
    group-id: kafka-dispatcher
    missing-topics-fatal: false
    topics:

server:
  port: 8080
  servlet:
    context-path: /dispatcher

dispatcher:
  mode: NON_BLOCKING
  service:
    topics:
      - name: oncorseq_sequencing_in_progress
        actions:
          - trigger: nextflow run main.nf --sampleID ${sampleID} --run ${runID} --sayHello ${sayHello}
            reply:
              topic:  oncorseq_sequencing_pipeline_initialized
              payload: sampleID=${sampleID}
      - name: oncorseq_sequencing_pipeline_initialized
        actions:
          - trigger: https://dzone.com/articles/kafka-cluster-1?q=${query}
            reply:
              topic: annotation_started
              payload: search started with ${query}
      - name: oncorseq_sequencing_analysis_started
        actions:
          - trigger: command/URL for analysis_started
            reply:
              topic: analysis_in_progress
              payload: ${sampleID}

  schedulers:
    enable: true
    cron:
      job1:
        active: true
        when: '*/10 * * * * ?'
        actions:
          - trigger: echo "cron job2 started at $(date)" >> $HOME/DispatcherSuite/kafka-service/jobs.txt
      job2:
        active: true
        when: '*/20 * * * * ?'
        actions:
          - trigger: echo "cron job2 started at $(date)" >> $HOME/DispatcherSuite/kafka-service/jobs.txt
    fixed:
      job1:
        active: true
        when: '10000'
        actions:
          - trigger: echo "fixed job1 started at $(date)"" >> $HOME/DispatcherSuite/kafka-service/jobs.txt
      job2:
        active: true
        when: '12000'
        actions:
          - trigger: echo "fixed job2 started at $(date)" >> $HOME/DispatcherSuite/kafka-service/jobs.txt
    delay:
      job1:
        active: true
        when: '15000'
        actions:
          - trigger: echo "delay job1 started at $(date)" >> $HOME/DispatcherSuite/kafka-service/jobs.txt
      job2:
        active: true
        when: '30000'
        actions:
          - trigger: echo "delay job2 started at $(date)" >> $HOME/DispatcherSuite/kafka-service/jobs.txt


logging:
  level:
    org.apache.kafka: INFO