spring:
  cloud:
    azure:
      credential-file-path: azure-credentials.json
      resource-group: LIMS
      region: West US 2
      eventhub:
        namespace: eipm-lims
    stream:
      bindings:
        input:
          destination: lims-messages
          group: eventhubdispatcherservice
        output:
          destination: lims-messages

server:
  port: 8080
  servlet:
    context-path: /dispatcher

dispatcher:
  mode: NON_BLOCKING
  service:
    topics:
      - name: oncorseq_sequencing_in_progress
        actions:
          - trigger: nextflow main.nf --sampleID ${sampleID} --run ${runID} --sayHello ${sayHello}
            reply:
              topic:  oncorseq_sequencing_pipeline_initialized
              payload: sampleID=${sampleID}
      - name: oncorseq_sequencing_pipeline_initialized
        actions:
          - trigger: https://dzone.com/articles/kafka-cluster-1?q=${query}
            reply:
              topic: annotation_started
              payload: search started with ${query}
      - name: oncorseq_sequencing_analysis_started
        actions:
          - trigger: command/URL for analysis_started
            reply:
              topic: analysis_in_progress
              payload: ${sampleID}

